### ISSUE TITLE
CDM Migrator Error - Attempting to Map AGGV Collection

### ISSUE THREAD

**Issue by deanseeman** [UVicLibrary/cdm_migrater#14]
Got this error when trying to map collections using http://vault.library.uvic.ca/cdm_migrator/cdm/collection

![cdm_migrator_error](https://user-images.githubusercontent.com/17652528/51500992-0e57c600-1d85-11e9-9728-ab89cca63f67.gif)

![cdm_migrator_error2](https://user-images.githubusercontent.com/17652528/51501108-773f3e00-1d85-11e9-8478-703022e3ada8.gif)

![cdm_migrator_error3](https://user-images.githubusercontent.com/17652528/51501112-79a19800-1d85-11e9-9187-f482db752c2a.gif)

**Comment by sephirothkod** [comment]
Qdrive got disconnected. It has been reconnected now
