### ISSUE TITLE
Mapping function broken because "collection" GET variable is missing

### ISSUE THREAD

**Issue by Steve-A-Orr** [UVicLibrary/cdm_migrater#8]
After selecting a collection to map, I receive the following error:
![screen shot 2018-06-12 at 15 57 29](https://user-images.githubusercontent.com/4119409/41321580-679aa876-6e59-11e8-96c3-f0f8fa043b81.png)

This is because the URL being used lacks the value for the "collection" GET variable. For example, after choosing the colleciton my URL would look like:
http://your-hyrax-host:3000/cdm_migrator/cdm/mappings?utf8=%E2%9C%93&collection=&work=Work&commit=choose+mappings

A snippet from the collection list JSON, for this collection, is:
```
{
  "alias": "\/hyrax",
  "name": "Hyrax Test",
  "path": "\/home\/Collections\/General\/hyrax",
  "remoteurl": false
}
```

In _cdm_controller.rb_, at line 93, you are calling for a JSON key of 'secondary_alias' which doesn't exist in my local instance of CONTENTdm; we have 'alias' available. (We run CONTENTdm Version 6.5.0.291s/6.5.0.549w currently, though we will be going to the OCLC SaaS soon.)

After entering the 'alias' key value of "hyrax" into the above URL, everything works as expected. The URL following this action is:
http://your-hyrax-host:3000/cdm_migrator/cdm/mappings?utf8=%E2%9C%93&collection=hyrax&work=Work&commit=choose+mappings

So, not knowing if your instance of CONTENTdm (_on which I assume this code is working_) is **customized** to provide 'secondary_alias' or if you're just on a **different version** than us, would it make sense to put this JSON key value string into the '_config/cdm_migrator.yml_' file along with the URL and port, so that it can be customized per installation; or should we put in logic to look for one key and then another if not found?

I'm willing to give you a Pull Request for one of these solutions, even though I'm not strong in Ruby/Rails, if you're accepting them for this project.

**Comment by sephirothkod** [comment]
Hi Steven,

Just seeing this now, I don't believe we customized the secondary_alias key, so it must be that we are running a different version. We are looking at making the api calls customizable in the yml during our next sprint in July.
Any code you are willing to contribute is greatly appreciated.
